services:
  #Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/no_folder/loki_syslog_aio_overview.json
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-storage:/var/lib/grafana
  ##################################################################
  #cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
  ##################################################################
  #loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    depends_on:
      - minio
    ports:
      - "3100:3100"
    restart: always
    volumes:
      - ./config/loki/loki-config-s3.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
  ##################################################################
  #minio
  minio:
    image: minio/minio:latest
    container_name: minio
    entrypoint: sh
    command: -c 'mkdir -p /data/loki && /usr/bin/docker-entrypoint.sh minio server /data'
    environment:
      MINIO_ACCESS_KEY: minio123
      MINIO_SECRET_KEY: minio456
      MINIO_PROMETHEUS_AUTH_TYPE: public
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      timeout: 20s
    ports:
      - "9000"
    restart: always
  ##################################################################
  #node-exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command: --path.rootfs=/host
    pid: host
    ports:
      - "9100:9100"
    restart: always
    volumes:
      - /:/host:ro,rslave
  ##################################################################
  #prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  ##################################################################
  #syslog-ng
  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng
    command: -edv
    depends_on:
      - promtail
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    restart: always
    volumes:
      - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
  ##################################################################
  #promtail
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    ports:
      - "1514:1514/tcp"
      - "9080:9080/tcp"
    restart: always
    volumes:
      - ./config/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - prometheus_data:/prometheus

volumes:
  grafana-storage: {}
  loki-data: {}
  prometheus_data: {}
